env:
  - CGO_ENABLED=0
builds:
  - targets:
      - linux_amd64
      - linux_arm64
archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: '{{ .Version }}_checksums.txt'
changelog:
  use: github-native
