name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

  release:
    types: [published]

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Remove all permissions by default
permissions: {}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: '^1.25' # The Go version to download (if necessary) and use.
      - name: Install Build Dependencies
        run: make get-build-deps
      - name: Download required modules
        run: make download
      - name: Vet
        run: make vet
      - name: Lint
        run: make lint
      - name: Cover
        run: make cover
      - name: Build
        run: |
          set -ex
          for dist in amd64 arm64; do
             target=out/wait-for-port-linux-$dist
             rm -rf "$target"
             make build/$dist TOOL_PATH="$target"
             file $target
             tar -C "$(dirname "$target")" -czf "$target.tar.gz" "$(basename "$target")"
          done
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: built-binaries
          path: |
            out/*.tar.gz
  release:
    needs: [ 'build-and-test' ]
    permissions:
      contents: write
    if: github.repository == 'bitnami/wait-for-port' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          path: ./artifacts
      - name: Set tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Release
        run: |
          set -e
          create_digest_file() {
              local digest_file=${1:?You must provide the digest file path}
              shift
              for file in "$@"; do
                (
                   cd "$(dirname "$file")"
                   sha256sum "$(basename "$file")"
                ) >> "$digest_file"
              done
          }
          assets=( ./artifacts/built-binaries/*.gz )

          tag_name="${{ steps.vars.outputs.tag }}"
          checksums_file="${tag_name}_checksums.txt"
          create_digest_file "$checksums_file" "${assets[@]}"
          assets+=( "$checksums_file" )
          if gh release view "$tag_name" >/dev/null 2>/dev/null; then
            echo "Release $tag_name already exists. Updating"
            gh release upload "$tag_name" "${assets[@]}"
          else
            echo "Creating new release $tag_name"
            # Format checksums for the release text
            printf '```\n%s\n```' "$(<"$checksums_file")" > release.txt
            gh release create -t "$tag_name" "$tag_name" -F release.txt "${assets[@]}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  notify:
    name: Send notification
    needs:
      - release
    if: ${{ always() && needs.release.result == 'failure' }}
    uses: bitnami/support/.github/workflows/gchat-notification.yml@main
    with:
      workflow: ${{ github.workflow }}
      job-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets:
      webhook-url: ${{ secrets.GCHAT_CONTENT_ALERTS_WEBHOOK_URL }}
